# Generated by Django 5.0.3 on 2024-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
